% script to initialize HydroBase3 properties
global HB_INITIALIZED HB_PROP_INFO HB_MISSING
global GAP_SHALLOW GAP_DEEP

HB_MISSING = -9.0;
GAP_SHALLOW = 210;
GAP_DEEP = 610;
HB_PROP_INFO = { ...
 'pr','pressure','dbars','%8.1f', ; ...
 'de','depth','meters','%8.1f', ; ...
 'te','in situ temperature IPTS-68','degrees C','%8.4f', ; ...
 'th','potential temperature: pref= 0.','degrees C','%8.4f', ; ...
 't90','in situ temperature ITS-90','degrees C','%8.4f', ; ...
 'th9','potential temperature ITS-90','degrees C','%8.4f', ; ...
 'sa','salinity','psu','%8.4f', ; ...
 'ox','oxygen','ml/liter','%8.3f', ; ...
 'o2','oxygen','micromole/kg','%8.1f', ; ...
 'n2','nitrite','micromole/kg','%8.3f', ; ...
 'n3','nitrate','micromole/kg','%8.3f', ; ...
 'p4','phosphate','micromole/kg','%8.3f', ; ...
 'si','silicate','micromole/kg','%8.3f', ; ...
 'ht','dynamic height','dyn. meters (= *10 m**2/s**2)',  '%8.3f', ; ...
 'pe','potential energy anomaly','10**6 g/sec**2 (ergs/cm**2)','%10.1f', ; ...
 's0','potential density: pref = 0.','kg/m**3','%8.4f', ; ...
 's1','potential density: pref = 1000.','kg/m**3','%8.4f', ; ...
 's2','potential density: pref = 2000.','kg/m**3','%8.4f', ; ...
 's3','potential density: pref = 3000.','kg/m**3','%8.4f', ; ...
 's4','potential density: pref = 4000.','kg/m**3','%8.4f', ; ...
 's_','potential density: pref = ?.','kg/m**3','%8.4f', ; ...
 'bf','buoyancy frequency','* 1.e-5 radians/sec','%10.4f', ; ...
 'pv','potential vorticity','* 1.e-12 m^-1 sec^-1','%10.3f', ; ...
 'sv','specific volume','* 1.e-8 m**3/kg','%10.3f', ; ...
 'va','specific volume anomaly','* 1.e-8 m**3/kg','%8.4f', ; ...
 'f1','cfc-11','picomole/kg','%8.3f', ; ...
 'f2','cfc-12','picomole/kg','%8.3f', ; ...
 'f3','cfc-113','picomole/kg','%8.3f', ; ...
 'he','helium','micromole/kg','%8.3f', ; ...
 'tu','tritium','tritium units','%8.3f', ; ...
 'gn','neutral density (gamma-n)','kg/m**3','%8.4f', ; ...
 'ge','gamma-n errorbar','kg/m**3','%8.5f', ; ...
 'vn','velocity north','m/sec','%9.4f', ; ...
 've','velocity east','m/sec','%9.4f', ; ...
 'vs','sound velocity','m/sec','%9.3f', ; ...
 'dr','density ratio','','%8.4f', ; ...
 'al','thermal expansion','*1.e7 alpha','%9.1f', ; ...
 'be','haline contraction', '*1.e7 beta','%9.1f',; ...
 'ccl','carbon tetrachloride', '[picomole/kg]','%8.3f',;...
'sf6', 'sulfur hexafluoride', '[femtomoles/kg]','%8.3f',;...
'co2', 'total carbon dioxide', '[micromole/kg]','%8.1f',;...
'alk', 'total alkalinity', '[micromole/kg]','%8.1f', ; ...
'doc', 'dissolved organic carbon', '[micromole/kg]','%8.2f',;...
'tdn', 'total dissolved nitrogen', '[micromole/kg]','%8.2f',;...
'c14', 'radiocarbon-14', '[/mille]', '%8.1f', ;...
'c13', 'radiocarbon-13', '[/mille]', '%8.2f', ;...
 'x1','extra variable', 'units', '%10.3g', ; ...
 'x2','extra variable', 'units', '%10.3g', ; ...
 'x3','extra variable', 'units', '%10.3g'};

HB_INITIALIZED = 1;